"""empty message

Revision ID: d62deb32d32e
Revises: 3bed557a94e4
Create Date: 2022-11-24 18:02:30.974067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62deb32d32e'
down_revision = '3bed557a94e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userName', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'userName')
    # ### end Alembic commands ###
